### ISSUE TITLE
Img2Img and inpainting no longer working with 1.5

### ISSUE THREAD

**Issue by coffeeorgreentea** [kiri-art/docker-diffusers-api#5]
They are returning brand new images. Same code works with 1.4

Edit:
For clarity, the inpainting works with runwayml/stable-diffusion-inpainting but doing either img2img or inpainting with runwayml/stable-diffusion-v1-5 returns brand new images

**Comment by gadicc** [comment]
Thanks for reporting, @coffeeorgreentea.

To my great shame, this was a result of two typos I made while trying to get this out before the weekend :/

Sincerely apologise for any time you spent fighting with this :/

🙇

Please confirm when you have a chance that this is working now.

**Comment by coffeeorgreentea** [comment]
Working great now! Thanks for your hard work!
